Watchlist.destroy_all
User.destroy_all
Movie.destroy_all

Movie.create(title: "The Shawshank Redemption", year: 1994, rating: 90, genre: 'Drama')
Movie.create(title: "GoodFellas", year: 1990, rating: 96, genre: 'Drama')
Movie.create(title: "The Pianist", year: 2002, rating: 95, genre: 'Drama')
Movie.create(title: "3 Idiots", year: 2009, rating: 100, genre: 'Drama')
Movie.create(title: "Inglourious Basterds", year: 2009, rating: 89, genre: 'Drama')
Movie.create(title: "Taxi Driver", year: 1976, rating: 97, genre: 'Drama')
Movie.create(title: "Pan's Labyrinth", year: 2006, rating: 95, genre: 'Drama')
Movie.create(title: "Blade Runner", year: 1982, rating: 90, genre: 'Drama')
Movie.create(title: "Room", year: 2015, rating: 93, genre: 'Drama')
Movie.create(title: "The King's Speech", year: 2010, rating: 95, genre: 'Drama')
Movie.create(title: "Her", year: 2013, rating: 95, genre: 'Drama')
Movie.create(title: "There Will Be Blood", year: 2007, rating: 91, genre: 'Drama')
Movie.create(title: "The Social Network", year: 2010, rating: 96, genre: 'Drama')
Movie.create(title: "3 Idiots", year: 2009, rating: 100, genre: 'Comedy')
Movie.create(title: "Monty Python and the Holy Grail", year: 1975, rating: 97, genre: 'Comedy')
Movie.create(title: "Groundhog Day", year: 1993, rating: 96, genre: 'Comedy')
Movie.create(title: "Life of Brian", year: 1979, rating: 95, genre: 'Comedy')
Movie.create(title: "Silver Linings Playbook", year: 2012, rating: 92, genre: 'Comedy')
Movie.create(title: "Marriage Story", year: 2019, rating: 95, genre: 'Comedy')
Movie.create(title: "Incredibles 2", year: 2018, rating: 94, genre: 'Comedy')
Movie.create(title: "Ferris Bueller's Day Off", year: 1986, rating: 80, genre: 'Comedy')
Movie.create(title: "The Hangover", year: 2009, rating: 78, genre: 'Comedy')
Movie.create(title: "The Hateful Eight", year: 2015, rating: 75, genre: 'Comedy')
Movie.create(title: "Scott Pilgrim vs. the World", year: 2010, rating: 81, genre: 'Comedy')
Movie.create(title: "To All the Boys I've Loved Before", year: 2020, rating: 97, genre: 'Comedy')
Movie.create(title: "Ant-Man and the Wasp", year: 2018, rating: 88, genre: 'Comedy')
Movie.create(title: "As Good as It Gets", year: 1997, rating: 85, genre: 'Comedy')
Movie.create(title: "Back to the Future Part III", year: 1990, rating: 79, genre: 'Comedy')
Movie.create(title: "The Naked Gun: From the Files of Police Squad!", year: 1988, rating: 87, genre: 'Comedy')
Movie.create(title: "The Edge of Seventeen", year: 2016, rating: 94, genre: 'Comedy')
Movie.create(title: "Y Tu Mamá También", year: 2001, rating: 92, genre: 'Comedy')
Movie.create(title: "Kung Fu Hustle", year: 2004, rating: 90, genre: 'Comedy')
Movie.create(title: "Tucker and Dale vs. Evil", year: 2010, rating: 85, genre: 'Comedy')
Movie.create(title: "Dolemite Is My Name", year: 2019, rating: 97, genre: 'Comedy')
Movie.create(title: "Jerry Maguire", year: 1996, rating: 83, genre: 'Comedy')
Movie.create(title: "Saving Mr. Banks", year: 2013, rating: 79, genre: 'Comedy')
Movie.create(title: "The Spectacular Now", year: 2013, rating: 91, genre: 'Comedy')
Movie.create(title: "The Lobster", year: 2015, rating: 88, genre: 'Comedy')
Movie.create(title: "Kung Fu Panda 2", year: 2011, rating: 81, genre: 'Comedy')
Movie.create(title: "PK", year: 2014, rating: 76, genre: 'Comedy')
Movie.create(title: "Tootsie", year: 1982, rating: 90, genre: 'Comedy')
Movie.create(title: "Bad Genius", year: 2017, rating: 100, genre: 'Comedy')
Movie.create(title: "The Death of Stalin", year: 2017, rating: 96, genre: 'Comedy')
Movie.create(title: "The Ballad of Buster Scruggs", year: 2018, rating: 91, genre: 'Comedy')
Movie.create(title: "The Squid and the Whale", year: 2005, rating: 92, genre: 'Comedy')
Movie.create(title: "Jim & Andy: The Great Beyond- Featuring a Very Special, Contractually Obligated Mention of Tony Clifton", year: 2017, rating: 96, genre: 'Comedy')
Movie.create(title: "Chasing Amy", year: 1997, rating: 87, genre: 'Comedy')
Movie.create(title: "Bolt", year: 2008, rating: 89, genre: 'Comedy')
Movie.create(title: "Frances Ha", year: 2013, rating: 92, genre: 'Comedy')
Movie.create(title: "Tremors", year: 1990, rating: 88, genre: 'Comedy')
Movie.create(title: "Zindagi Na Milegi Dobara", year: 2011, rating: 91, genre: 'Comedy')
Movie.create(title: "Padman", year: 2018, rating: 100, genre: 'Comedy')
Movie.create(title: "The Croods", year: 2013, rating: 71, genre: 'Comedy')
Movie.create(title: "Barfi!", year: 2012, rating: 86, genre: 'Comedy')
Movie.create(title: "Queen", year: 2013, rating: 86, genre: 'Comedy')
Movie.create(title: "Austin Powers: International Man of Mystery", year: 1997, rating: 70, genre: 'Comedy')
Movie.create(title: "Bill Burr: I'm Sorry You Feel That Way", year: 2014, rating: 100, genre: 'Comedy')
Movie.create(title: "Christopher Robin", year: 2018, rating: 73, genre: 'Comedy')
Movie.create(title: "Harold & Kumar Go to White Castle", year: 2004, rating: 74, genre: 'Comedy')
Movie.create(title: "Driving Miss Daisy", year: 1989, rating: 81, genre: 'Comedy')
Movie.create(title: "A Serious Man", year: 2009, rating: 90, genre: 'Comedy')
Movie.create(title: "The Mask of Zorro", year: 1998, rating: 82, genre: 'Comedy')
Movie.create(title: "Hannah Gadsby: Nanette", year: 2018, rating: 100, genre: 'Comedy')
Movie.create(title: "Train to Busan", year: 2016, rating: 94, genre: 'Horror')
Movie.create(title: "Rosemary's Baby", year: 1968, rating: 96, genre: 'Horror')
Movie.create(title: "The Evil Dead", year: 1981, rating: 95, genre: 'Horror')
Movie.create(title: "Sweeney Todd: The Demon Barber of Fleet Street", year: 2007, rating: 85, genre: 'Horror')
Movie.create(title: "Tucker and Dale vs. Evil", year: 2010, rating: 85, genre: 'Horror')
Movie.create(title: "Green Room", year: 2015, rating: 91, genre: 'Horror')
Movie.create(title: "The Wicker Man", year: 1973, rating: 89, genre: 'Horror')
Movie.create(title: "Tremors", year: 1990, rating: 88, genre: 'Horror')
Movie.create(title: "Hush", year: 2016, rating: 91, genre: 'Horror')
Movie.create(title: "Gerald's Game", year: 2017, rating: 90, genre: 'Horror')
Movie.create(title: "The Witch", year: 2015, rating: 90, genre: 'Horror')
Movie.create(title: "The Autopsy of Jane Doe", year: 2016, rating: 86, genre: 'Horror')
Movie.create(title: "The Killing of a Sacred Deer", year: 2017, rating: 79, genre: 'Horror')
Movie.create(title: "The Invitation", year: 2015, rating: 88, genre: 'Horror')
Movie.create(title: "The Ring", year: 2002, rating: 71, genre: 'Horror')
Movie.create(title: "Insidious", year: 2010, rating: 66, genre: 'Horror')
Movie.create(title: "The Endless", year: 2018, rating: 94, genre: 'Horror')
Movie.create(title: "Under the Shadow", year: 2016, rating: 99, genre: 'Horror')
Movie.create(title: "The Girl with All the Gifts", year: 2016, rating: 85, genre: 'Horror')
Movie.create(title: "Stree", year: 2018, rating: 77, genre: 'Horror')
Movie.create(title: "The Perfection", year: 2018, rating: 83, genre: 'Horror')
Movie.create(title: "1922", year: 2017, rating: 90, genre: 'Horror')
Movie.create(title: "Creep 2", year: 2017, rating: 100, genre: 'Horror')
Movie.create(title: "Scream 2", year: 1997, rating: 82, genre: 'Horror')
Movie.create(title: "Child's Play", year: 1988, rating: 68, genre: 'Horror')
Movie.create(title: "Candyman", year: 1992, rating: 74, genre: 'Horror')
Movie.create(title: "It Comes at Night", year: 2017, rating: 87, genre: 'Horror')
Movie.create(title: "Veronica", year: 2017, rating: 88, genre: 'Horror')
Movie.create(title: "Final Destination", year: 2000, rating: 34, genre: 'Horror')
Movie.create(title: "The Platform", year: 2019, rating: 84, genre: 'Horror')
Movie.create(title: "The Ritual", year: 2017, rating: 71, genre: 'Horror')
Movie.create(title: "The Babysitter", year: 2017, rating: 71, genre: 'Horror')
Movie.create(title: "Hold the Dark", year: 2018, rating: 73, genre: 'Horror')
Movie.create(title: "The Craft", year: 1996, rating: 55, genre: 'Horror')
Movie.create(title: "Cam", year: 2018, rating: 93, genre: 'Horror')
Movie.create(title: "Event Horizon", year: 1997, rating: 27, genre: 'Horror')
Movie.create(title: "The Gift", year: 2000, rating: 57, genre: 'Horror' )
Movie.create(title: "He Never Died", year: 2015, rating: 87, genre: 'Horror')
Movie.create(title: "What Lies Beneath", year: 2000, rating: 46, genre: 'Horror')
Movie.create(title: "Killer Klowns from Outer Space", year: 1988, rating: 77, genre: 'Horror')
Movie.create(title: "Berlin Syndrome", year: 2017, rating: 75, genre: 'Horror')
Movie.create(title: "Final Destination 2", year: 2003, rating: 48, genre: 'Horror')
Movie.create(title: "Stonehearst Asylum", year: 2014, rating: 54, genre: 'Horror')
Movie.create(title: "Carriers", year: 2009, rating: 67, genre: 'Horror')
Movie.create(title: "Resident Evil: Extinction", year: 2007, rating: 24, genre: 'Horror')
Movie.create(title: "Resident Evil: Apocalypse", year: 2004, rating: 20, genre: 'Horror')
Movie.create(title: "The Forest of Love", year: 2019, rating: 100, genre: 'Horror')
Movie.create(title: "Errementari: The Blacksmith and the Devil", year: 2018, rating: 67, genre: 'Horror')
Movie.create(title: "Before I Wake", year: 2016, rating: 61, genre: 'Horror')
Movie.create(title: "Aval", year: 2017, rating: 100, genre: 'Horror')
Movie.create(title: "Inception", year: 2010, rating: 87, genre: 'Action')
Movie.create(title: "Avengers: Infinity War", year: 2018, rating: 85, genre: 'Action')
Movie.create(title: "The Matrix", year: 1999, rating: 87, genre: 'Action')
Movie.create(title: "Raiders of the Lost Ark", year: 1981, rating: 95, genre: 'Action')
Movie.create(title: "Spider-Man: Into the Spider-Verse", year: 2018, rating: 97, genre: 'Action')
Movie.create(title: "Inglourious Basterds", year: 2009, rating: 89, genre: 'Action')
Movie.create(title: "Once Upon a Time in the West", year: 1968, rating: 95, genre: 'Action')
Movie.create(title: "Monty Python and the Holy Grail", year: 1975, rating: 97, genre: 'Action')
Movie.create(title: "Indiana Jones and the Last Crusade", year: 1989, rating: 88, genre: 'Action')
Movie.create(title: "Drive", year: 2011, rating: 92, genre: 'Action')
Movie.create(title: "Train to Busan", year: 2016, rating: 94, genre: 'Action')
Movie.create(title: "Incredibles 2", year: 2018, rating: 94, genre: 'Action')
Movie.create(title: "Minority Report", year: 2002, rating: 90, genre: 'Action')
Movie.create(title: "Klaus", year: 2019, rating: 94, genre: 'Action')
Movie.create(title: "Crouching Tiger, Hidden Dragon", year: 2000, rating: 97, genre: 'Action')
Movie.create(title: "Dangal", year: 2016, rating: 88, genre: 'Action')
Movie.create(title: "Ip Man", year: 2008, rating: 85, genre: 'Action')
Movie.create(title: "Indiana Jones and the Temple of Doom", year: 1984, rating: 85, genre: 'Action')
Movie.create(title: "Scott Pilgrim vs. the World", year: 2010, rating: 81, genre: 'Action')
Movie.create(title: "Hugo", year: 2011, rating: 93, genre: 'Action')
Movie.create(title: "Ant-Man and the Wasp", year: 2018, rating: 88, genre: 'Action')
Movie.create(title: "Sherlock Holmes", year: 2009, rating: 70, genre: 'Action')
Movie.create(title: "Snowpiercer", year: 2013, rating: 95, genre: 'Action')
Movie.create(title: "El Camino: A Breaking Bad Movie", year: 2019, rating: 91, genre: 'Action')
Movie.create(title: "Lethal Weapon", year: 1987, rating: 82, genre: 'Action')
Movie.create(title: "End of Watch", year: 2012, rating: 85, genre: 'Action')
Movie.create(title: "Dirty Harry", year: 1971, rating: 89, genre: 'Action')
Movie.create(title: "Y Tu Mamá También", year: 2001, rating: 92, genre: 'Action')
Movie.create(title: "The Last Samurai", year: 2003, rating: 66, genre: 'Action')
Movie.create(title: "Kung Fu Hustle", year: 2004, rating: 90, genre: 'Action')
Movie.create(title: "Bahubali: The Beginning", year: 2015, rating: 88, genre: 'Action')
Movie.create(title: "Tarzan", year: 1999, rating: 89, genre: 'Action')
Movie.create(title: "Lagaan: Once Upon a Time in India", year: 2001, rating: 95, genre: 'Action')
Movie.create(title: "GoldenEye", year: 1995, rating: 78, genre: 'Action')
Movie.create(title: "Okja", year: 2017, rating: 87, genre: 'Action')
Movie.create(title: "The Dawn Wall", year: 2018, rating: 100, genre: 'Action')
Movie.create(title: "The Matrix Reloaded", year: 2003, rating: 73, genre: 'Action')
Movie.create(title: "Baahubali 2: The Conclusion", year: 2017, rating: 89, genre: 'Action')
Movie.create(title: "The Little Prince", year: 2015, rating: 93, genre: 'Action')
Movie.create(title: "Ip Man 2", year: 2010, rating: 96, genre: 'Action')
Movie.create(title: "Ralph Breaks the Internet", year: 2018, rating: 88, genre: 'Action')
Movie.create(title: "Kung Fu Panda 2", year: 2011, rating: 81, genre: 'Action')
Movie.create(title: "The Dirty Dozen", year: 1967, rating: 86, genre: 'Action')
Movie.create(title: "Cloverfield", year: 2008, rating: 77, genre: 'Action')
Movie.create(title: "The Adventures of Tintin", year: 2011, rating: 74, genre: 'Action')
Movie.create(title: "The Princess and the Frog", year: 2009, rating: 85, genre: 'Action')
Movie.create(title: "Bolt", year: 2008, rating: 89, genre: 'Action')
Movie.create(title: "Neon Genesis Evangelion: The End of Evangelion", year: 1997, rating: 88, genre: 'Action')
Movie.create(title: "Lethal Weapon 2", year: 1989, rating: 84, genre: 'Action')
Movie.create(title: "Zindagi Na Milegi Dobara", year: 2011, rating: 91, genre: 'Action')